root = "."
tmp_dir = "tmp"
poll = true

[build]
  cmd = "go build -C ./metrics-server -o ../tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]
