apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: default
  labels:
    app: metrics-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: metrics-server:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi
        #   limits:
        #     cpu: 500m
        #     memory: 256Mi
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        hostPath:
          path: /app
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: default
spec:
  type: NodePort
  selector:
    app: metrics-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 8080
